version: "2"
services:
  node:
    image: "digitallyseamless/nodejs-bower-grunt"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "grunt"